version: "3.9"

services:
  add-remote-a:
    environment:
      - ADVERTISED_HOST=add-remote-a
      - ADVERTISED_PORT=80
      - TARGET_PID=add-remote-b:80
    image: add-remote
    build:
      context: .
      dockerfile: AddRemote/Dockerfile
    networks:
      - my-network
  add-remote-b:
    environment:
      - ADVERTISED_HOST=add-remote-b
      - ADVERTISED_PORT=80
      - TARGET_PID=add-remote-a:80
    image: add-remote
    depends_on:
      - add-remote-a
    networks:
      - my-network
  with-remote-a:
    environment:
      - ADVERTISED_HOST=with-remote-a
      - ADVERTISED_PORT=80
      - TARGET_PID=with-remote-b:80
    image: with-remote
    build:
      context: .
      dockerfile: WithRemote/Dockerfile
    networks:
      - my-network
  with-remote-b:
    environment:
      - ADVERTISED_HOST=with-remote-b
      - ADVERTISED_PORT=80
      - TARGET_PID=with-remote-a:80
    image: with-remote
    depends_on:
      - with-remote-a
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
